"""Export to a FiveM resource folder: stream/ with the assets, plus an fxmanifest.lua that loads the YTYP files."""

from pathlib import Path

import bpy
from bpy.app.translations import pgettext_rpt as rpt_

from . import compat, doctor


class ExportError(Exception):
    """A problem the user can act on."""


MANIFEST = """fx_version 'cerulean'
game 'gta5'
lua54 'yes'

description '{description}'
{map_line}
files {{
    'stream/*.ytyp',
}}

{data_files}
"""


def manifest_text(resource, ytyps, is_map=False):
    data_files = "\n".join(f"data_file 'DLC_ITYP_REQUEST' 'stream/{name}'" for name in sorted(ytyps))
    return MANIFEST.format(
        description=f"{resource} (generated by FiveM Toolkit for Blender)",
        map_line="this_is_a_map 'yes'\n" if is_map else "",
        data_files=data_files,
    )


def export(context, s):
    """Write the resource folder. Returns (resource path, list of exported file names)."""
    try:
        compat.require()
    except compat.SollumzMissing as e:
        raise ExportError(str(e)) from e
    if not s.output_dir:
        raise ExportError(rpt_("Choose an output folder first."))
    sc = context.scene
    targets = compat.drawables(context, s.selected_only)
    roots = (compat.COMPOSITE, "sollumz_drawable_dictionary", compat.FRAGMENT)  # collision files, ped components, ...
    targets += [
        o
        for o in (context.selected_objects if s.selected_only else sc.objects)
        if compat.kind(o) in roots and o.parent is None
    ]
    if not targets and not len(sc.ytyps):
        raise ExportError(rpt_("There is nothing to export: build a prop first."))
    resource = Path(bpy.path.abspath(s.output_dir)) / s.resource_name
    stream = resource / "stream"
    stream.mkdir(parents=True, exist_ok=True)

    if targets:
        compat.select_only(context, *targets)
    wanted = dict(
        directory=str(stream),
        use_custom_settings=True,
        direct_export=True,
        target_formats={s.export_format},
        target_versions={"GEN8"},
        limit_to_selected=bool(targets),
        export_ytyps=True,
        export_ytyps_include="ALL",
        export_ytds=True,
        export_ytds_include="ALL",
    )
    result = compat.call(bpy.ops.sollumz.export_assets, **wanted)
    if "export_ytyps" not in {p.identifier for p in bpy.ops.sollumz.export_assets.get_rna_type().properties}:
        compat.call(
            bpy.ops.sollumz.export_ytyp_io,
            directory=str(stream),
            use_custom_settings=True,
            target_formats={s.export_format},
            target_versions={"GEN8"},
        )  # older Sollumz: separate YTYP export
    if result != {"FINISHED"}:
        raise ExportError(rpt_("Sollumz could not export; open the Info Log for details."))
    files = sorted(p.name for p in stream.iterdir())
    # CodeWalker XML has to be converted to binary before FiveM can load it; the manifest already names the binary files
    ytyps = [n.removesuffix(".xml") for n in files if n.endswith((".ytyp", ".ytyp.xml"))]
    (resource / "fxmanifest.lua").write_text(manifest_text(s.resource_name, ytyps), encoding="utf-8")
    return resource, files


def problems_before_export(context, s):
    """Errors from the Doctor that would produce a broken resource."""
    pool = compat.drawables(context, s.selected_only)
    return [p for p in doctor.scan(pool, s) if p["severity"] == doctor.ERROR]
